
name = "svelteKit_color_themes"
compatibility_date = "2025-12-08"

main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = ["nodejs_compat"]

# Bind your static output directory (e.g. the client folder SvelteKit emitted)
[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
